services:
#Sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    # network_mode: "container:gluetun"
    ports:
      - 8989:8989 #Sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config #Sonarr Config
      - ${TVSHOWS}:/tv #TV Shows Folder
      - ${DOWNLOADS}:/downloads #Downloads
    restart: unless-stopped
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.10
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.sonarr-secure.entrypoints=https"
    #   - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.media.${DOMAIN}`)||Host(`sonarr.${DOMAIN}`)"
    #   - "traefik.http.routers.sonarr-secure.tls=true"
    #   - "traefik.http.routers.sonarr-secure.tls.certresolver=cloudflare"
    #   - "traefik.http.services.sonarr-service.loadbalancer.server.port=8989"
networks:
  servarrnetwork:
    external: true
