services:
#Sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    # network_mode: "container:gluetun"
    ports:
      - 8989:8989 #Sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/sonarr:/config #Sonarr Config
      - ${TVSHOWS}:/tv #TV Shows Folder
      - ${DOWNLOADS}:/downloads #Downloads
    restart: unless-stopped

    labels:
  # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
