services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - redis
    container_name: docmost
    environment:
      APP_URL: https://docmost.${DOMAIN}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      #DATABASE_URL=postgres://user:password@db_container_name:5432/dbname
      REDIS_URL: ${REDIS_URL}
      HOST: "0.0.0.0"
      JWT_TOKEN_EXPIRES_IN: ${JWT_TOKEN_EXPIRES_IN}
      MAIL_DRIVER: ${MAIL_DRIVER}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: ${SMTP_SECURE}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      PORT: ${PORT}
    ports:
      - "9093:9093"
    labels:
      - "traefik.enable=true"

      # HTTP redirect to HTTPS
      - "traefik.http.routers.docmost.entrypoints=http"
      - "traefik.http.routers.docmost.rule=Host(`notes.${DOMAIN}`)||Host(`notes.apps.${DOMAIN}`)"
      - "traefik.http.routers.docmost.middlewares=docmost-https-redirect"
      - "traefik.http.middlewares.docmost-https-redirect.redirectscheme.scheme=https"

      # HTTPS route
      - "traefik.http.routers.docmost-secure.entrypoints=https"
      - "traefik.http.routers.docmost-secure.rule=Host(`notes.${DOMAIN}`)||Host(`notes.apps.${DOMAIN}`)"
      - "traefik.http.routers.docmost-secure.tls=true"
      - "traefik.http.routers.docmost-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.docmost-secure.service=docmost-service"

      # Enable WebSocket headers via middleware
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.routers.docmost-secure.middlewares=docmost-https-redirect,websocket"

      # Target internal app port
      - "traefik.http.services.docmost-service.loadbalancer.server.port=9093"

    restart: unless-stopped
    volumes:
      - ./config:/app/data/storage
    networks:
      - frontend
      - backend

  redis:
    image: redis:7.2-alpine
    container_name: redis-docmost
    restart: unless-stopped
    volumes:
      - ./redis_data:/data
    networks:
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true