#Watchtower - update Docker Containers automatically
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: apps-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 86400
    environment:
      - WATCHTOWER_CLEANUP=true
    restart: unless-stopped