services:
  rotki:
    image: rotki/rotki:latest
    container_name: rotki
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      TZ: Europe/London
      PUID: 1001
      PGID: 1001
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.rotki.service=rotki
      - traefik.http.routers.rotki.rule=Host(`networth.${DOMAIN}`)
      - traefik.http.routers.rotki.entrypoints=websecure
      - traefik.http.services.rotki.loadbalancer.server.port=80
      - traefik.http.routers.rotki.tls=true
      - traefik.http.routers.rotki.tls.certresolver=cloudflare
      - traefik.http.routers.rotki.middlewares=compresstraefik
      - traefik.http.middlewares.compresstraefik.compress=true
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - frontend
      - backend
networks:
  frontend:
    external: true
  backend:
    external: true
