services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: postgres_db_default
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - /mnt/homeserver-config/postgres/data:/var/lib/postgresql/data
    networks:
      - postgres
      - backend
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: postgres_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - ALLOW_SPECIAL_EMAIL_DOMAINS=True
    ports:
      - 8080:80
    networks:
      - postgres
      - frontend
      - backend

networks:
  postgres:
    external: true
  backend:
    external: true
  frontend:
    external: true