services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${CONFIG}/plex:/config
      - ${TVSHOWS}:/tv #TV Shows
      - ${MOVIES}:/movies #Movies
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:32400/web/index.html || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "host"
    # networks:
    #   - plex-apps
    # ports:
    #   - "32400:32400"
    #   - "1900:1900/udp"  # For DLNA
    #   - "3005:3005"      # For Plex Companion
    #   - "5353:5353/udp"  # For Bonjour/Avahi discovery
    #   - "8324:8324"      # For Roku via Plex Companion
    #   - "32410:32410/udp" # For GDM network discovery
    #   - "32412-32414:32412-32414/udp" # For GDM network discovery
    #   - "32469:32469"    # For DLNA media transfer
# networks:
#   plex-apps:
#     external: true