services:  
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    networks:
      - frontend
    container_name: n8n
    labels:
      - "traefik.enable=true"
      # HTTP Router
      - "traefik.http.routers.n8n.entrypoints=http"
      - "traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN}`)||Host(`n8n.apps.${DOMAIN}`)"
      - "traefik.http.middlewares.n8n-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.n8n.middlewares=n8n-https-redirect"
      # HTTPS Router
      - "traefik.http.routers.n8n-secure.entrypoints=https"
      - "traefik.http.routers.n8n-secure.rule=Host(`n8n.${DOMAIN}`)||Host(`n8n.apps.${DOMAIN}`)"
      - "traefik.http.routers.n8n-secure.tls=true"
      - "traefik.http.routers.n8n-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.n8n-secure.service=n8n-service"
      - "traefik.http.services.n8n-service.loadbalancer.server.port=5678"

      - "traefik.http.routers.n8n.middlewares=default-security-headers@file"
      #- "traefik.http.routers.n8n-secure.middlewares=n8n-headers"
      #- "traefik.http.routers.n8n-secure.middlewares=default-security-headers@file"







    environment:
      - N8N_HOST=n8n.${DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.${DOMAIN}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - PGID=1000
      - PUID=1000
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_TRUST_PROXY='true'
      - N8N_PROXY_HOPS=1
      #- N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    volumes:
      - ./config/n8n_data:/home/node/.n8n
      - ./data/local-files:/files

networks:
    frontend:
      external: true