services:  
  n8n:
    image: n8nio/n8n:latest
    restart: always
    networks:
      - frontend
    container_name: n8n
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      # HTTP Router
      - "traefik.http.routers.n8n.entrypoints=http"
      - "traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN}`) || Host(`n8n.apps.${DOMAIN}`)"
      - "traefik.http.middlewares.n8n-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.n8n.middlewares=n8n-https-redirect"
      # HTTPS Router
      - "traefik.http.routers.n8n-secure.entrypoints=https"
      - "traefik.http.routers.n8n-secure.rule=Host(`n8n.${DOMAIN}`) || Host(`n8n.apps.${DOMAIN}`)"
      - "traefik.http.routers.n8n-secure.tls=true"
      - "traefik.http.routers.n8n-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.n8n-secure.service=n8n-service"
      - "traefik.http.services.n8n-service.loadbalancer.server.port=5678"

      - "traefik.http.routers.n8n.middlewares=default-security-headers@file"
      #- "traefik.http.routers.n8n-secure.middlewares=n8n-headers"
      #- "traefik.http.routers.n8n-secure.middlewares=default-security-headers@file"

    environment:
      # General n8n configurations
      - N8N_HOST=n8n.${DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.${DOMAIN}/

      # Security configurations
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_TRUST_PROXY=true
      - N8N_PROXY_HOPS=1
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

      # Timezone configurations
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}

      # System configurations
      - NODE_ENV=production
      - PGID=1000
      - PUID=1000

      # Execution configurations
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=90   # keep 90 days

      # Feature configurations
      - N8N_RUNNERS_ENABLED=true
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_HIDE_UI_NAGS=true

      # Postgres configurations
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}

    volumes:
      - ${CONFIG_LOCATION}:/home/node/.n8n
      - ${DATA_LOCATION}:/files

networks:
    frontend:
      external: true