# Homepage Configuration
title: "GigaPlex"
subtitle: "Personal Media Server"
logo: "fas fa-diamond"

header: true 
footer: '<p>Created with <span class="has-text-danger">❤️</span> using <a href="https://bulma.io/">Bulma</a>, <a href="https://vuejs.org/">Vue.js</a> & <a href="https://fontawesome.com/">Font Awesome</a>. Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>'

columns: "3"
connectivityCheck: true

proxy:
  useCredentials: false 
  headers: 
    Test: "Example"
    Test1: "Example1"

defaults:
  layout: columns
  colorTheme: auto

theme: neon

colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"

links:
  - name: "Twitter"
    icon: "fab fa-twitter-square"
    url: "https://x.com/salakoay_ola"
    target: "_blank"
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/salakoayoola"
    target: "_blank"

services:
  - name: "Gigaplex Favorites"
    icon: "fas fa-star"
    items:
      - name: "Plex"
        logo: "assets/icons/plex.png"
        subtitle: "Stream movies and TV shows."
        tag: "media"
        tagstyle: "is-success"
        url: "https://plex.gigaplex.site/"
        target: "_blank"
      - name: "Immich"
        logo: "assets/icons/immich.png"
        subtitle: "Personal photo storage and sharing."
        tag: "media"
        tagstyle: "is-success"
        url: "https://photos.gigaplex.site"
        target: "_blank"
      - name: "HomeAssistant"
        logo: "assets/icons/home-assistant.png"
        subtitle: "Smart home automation."
        url: "https://ahssistant.click/"
        target: "_blank"
        tag: "home automation"

  - name: "Media Operations"
    icon: "fas fa-cogs"
    items:
      - name: "Radarr"
        logo: "assets/icons/radarr.png"
        subtitle: "Manage movies automation."
        url: "https://radarr.gigaplex.site/"
        tag: "media ops"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/icons/sonarr.png"
        subtitle: "TV series management."
        url: "https://sonarr.gigaplex.site/"
        target: "_blank"
        tag: "media ops"
      - name: "Prowlarr"
        logo: "assets/icons/prowlarr.png"
        subtitle: "Indexer aggregator."
        url: "https://prowlarr.gigaplex.site/"
        target: "_blank"
        tag: "server ops"
      - name: "Bazarr"
        logo: "assets/icons/bazarr.png"
        subtitle: "Subtitle management tool."
        url: "https://bazarr.gigaplex.site/"
        target: "_blank"
        tag: "media ops"
      - name: "Tautulli"
        logo: "assets/icons/tautulli.png"
        subtitle: "Monitor Plex server activity."
        url: "https://tautulli.gigaplex.site/"
        tag: "media ops"
        target: "_blank"

  - name: "Office"
    icon: "fas fa-briefcase"
    items:
      - name: "Docmost"
        logo: "assets/icons/docmost.png"
        subtitle: "Notion alternative, I guess"
        url: "https://docmost.gigaplex.site/"
        tag: "doc ops"
        target: "_blank"
      - name: "Grafana"
        logo: "assets/icons/grafana.png"
        subtitle: "Data visualisation, I guess"
        url: "https://grafana.gigaplex.site/"
        tag: "doc ops"
        target: "_blank"
      - name: "NextCloud"
        logo: "assets/icons/nextcloud.png"
        subtitle: "Cloud storage and collaboration."
        tag: "productivity"
        tagstyle: "is-info"
        url: "https://office.gigaplex.site"
        target: "_blank"


  - name: "Server Operations"
    icon: "fas fa-server"
    items:
      - name: "qBittorrent"
        logo: "assets/icons/qbittorrent.png"
        subtitle: "Efficient torrent management."
        url: "https://qbitt.gigaplex.site/"
        tag: "server ops"
        target: "_blank"
      - name: "Portainer"
        logo: "assets/icons/portainer.png"
        subtitle: "Container management platform."
        tag: "server ops"
        url: "https://portainer.gigaplex.site/"
        target: "_blank"
      - name: "Influx DB"
        logo: "assets/icons/influxdb.png"
        subtitle: "Container management platform."
        tag: "server ops"
        url: "https://influxdb.gigaplex.site/"
        target: "_blank"
      - name: "File Browser"
        logo: "assets/icons/file-browser.png"
        subtitle: "Manage and share files."
        url: "https://files.gigaplex.site"
        target: "_blank"
        tag: "server ops"
      - name: "OpenMediaVault"
        logo: "assets/icons/openmediavault.png"
        subtitle: "Network-attached storage management."
        url: "https://omv.gigaplex.site/"
        target: "_blank"
        tag: "server ops"

