services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: gigaplex-backrest
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - /home/ayoola/docker:/infrarr-docker:ro
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=Europe/London
    restart: unless-stopped
    ports:
      - 9898:9898