services:
  pulsarr:
    image: lakker/pulsarr:latest
    container_name: pulsarr
    ports:
      - "3003:3003"
    volumes:
      - ${CONFIG}/pulsarr:/app/data
      - .env:/app/.env
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    labels:
            # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"