templates:
  Genre:
    plex_search:
      genre: <<genre>>
    url_poster: <<poster>>
    sort_title: <<collection_name>>
    sync_mode: sync
    smart_label: originally_available.desc
  Set:
    optional:
      - collection
      - movie
      - list
      - imdb
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    tmdb_list: <<list>>
    imdb_list: <<imdb>>
    sync_mode: sync
    collection_order: release
    url_poster: <<poster>>
    sort_title: <<collection_name>>
  Marvel:
    tmdb_collection_details: <<collection>>
    sync_mode: sync
    collection_order: release
    url_poster: <<poster>>
    sort_title: Marvel Cinematic Universe
  TraktList: # New Trakt List Template
    trakt_list: <<trakt_list>>
    sync_mode: sync
    collection_order: release
    url_poster: <<poster>>
    sort_title: <<collection_name>>

collections:
  # Original Genre Collections
  Action:
    template: {name: Genre, genre: Action, poster: https://theposterdb.com/api/assets/52675 }
    summary: Action

  Adventure:
    template: {name: Genre, genre: Adventure, poster: https://theposterdb.com/api/assets/52672 }
    summary: Adventure

  Anime:
    template: {name: Genre, genre: Anime, poster: https://theposterdb.com/api/assets/123923 }
    summary: Anime

  Comedy:
    template: {name: Genre, genre: Comedy, poster: https://theposterdb.com/api/assets/52677 }
    summary: Comedy

  Drama:
    template: {name: Genre, genre: Drama, poster: https://theposterdb.com/api/assets/52676 }
    summary: Drama

  Cooking:
    template: {name: Genre, genre: Food,  poster: https://theposterdb.com/api/assets/168695 }
    summary: Cooking / Food

  Crime:
    template: {name: Genre, genre: Crime,  poster: https://theposterdb.com/api/assets/167978 }
    summary: Crime

  Horror:
    template: {name: Genre, genre: Horror, poster: https://theposterdb.com/api/assets/52659 }
    summary: Horror

  Martial Arts:
    template: {name: Genre, genre: Martial Arts, poster: https://theposterdb.com/api/assets/165296 }
    summary: Martial Arts

  Mystery:
    template: {name: Genre, genre: Mystery, poster: https://theposterdb.com/api/assets/254759 }
    summary: Mystery

  Science Fiction:
    template: {name: Genre, genre: Science Fiction, poster: https://theposterdb.com/api/assets/52661 }
    summary: Science Fiction

  Sport:
    template: {name: Genre, genre: Sport, poster: https://theposterdb.com/api/assets/167979 }
    summary: Sport

  Thriller:
    template: {name: Genre, genre: Thriller, poster: https://theposterdb.com/api/assets/52658 }
    summary: Thriller

  War:
    template: {name: Genre, genre: War, poster: https://theposterdb.com/api/assets/52688 }
    summary: War

  Western:
    template: {name: Genre, genre: Western, poster: https://theposterdb.com/api/assets/52687 }
    summary: Western

  # Original Movie Sets
  "Jurassic Park":
    template: {name: Set, collection: 328, poster: https://theposterdb.com/api/assets/162511 }
    summary: Jurassic Park Collection

  "Mad Max":
    template: {name: Set, collection: 8945, poster: https://theposterdb.com/api/assets/184549 }
    summary: Mad Max Collection

  "Matrix":
    template: {name: Set, collection: 2344, poster: https://theposterdb.com/api/assets/163913 }
    summary: Matrix Collection

  "Men In Black":
    template: {name: Set, collection: 86055, poster: https://theposterdb.com/api/assets/163929 }
    summary: Men In Black Collection

  "Pirates of the Caribbean":
    template: {name: Set, collection: 295, poster: https://theposterdb.com/api/assets/163404 }
    summary: Pirates of the Caribbean Collection

  "Quentin Tarantino":
    template: {name: Set, list: 8201544, poster: https://theposterdb.com/api/assets/167512 }
    summary: Quentin Tarantino Films

  "The Dark Knight":
    template: {name: Set, collection: 263, poster: https://theposterdb.com/api/assets/263847 }
    summary: The Dark Knight Trilogy

  "Despicable Me":
    template: {name: Set, collection: 86066, poster: https://theposterdb.com/api/assets/163000 }
    summary: Despicable Me Collection

  "Minions":
    template: {name: Set, collection: 544669, poster: https://theposterdb.com/api/assets/192196 }
    summary: Minions Collection

  "Star Wars":
    template: {name: Set, collection: 10, poster: https://theposterdb.com/api/assets/164120 }
    summary: Star Wars Collection

  "The Hobbit":
    template: {name: Set, collection: 121938, poster: https://theposterdb.com/api/assets/187486 }
    summary: The Hobbit Trilogy

  "The Lord of the Rings":
    template: {name: Set, collection: 119, poster: https://theposterdb.com/api/assets/52722 }
    summary: The Lord of the Rings Trilogy

  # New Collections
  "Marvel Cinematic Universe":
    template: {name: Marvel, collection: 86311, poster: https://theposterdb.com/api/assets/167369, summary: Official Marvel Cinematic Universe films in chronological order}

  "Deadpool":
    template: {name: Marvel, collection: 495743, poster: https://theposterdb.com/api/assets/163328, summary: Ryan Reynolds' Deadpool franchise}

  "Oscar Best Picture Winners":
    smart_filter:
      all:
        awards: oscar best picture
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/167980
    summary: Films that have won the Academy Award for Best Picture

  "Critically Acclaimed Films":
    smart_filter:
      any:
        critic_rating.gt: 85
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/167981
    summary: Highest-rated films based on critic reviews

  "Christopher Nolan Collection":
    smart_filter:
      all:
        director: Christopher Nolan
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/167512
    summary: Films directed by Christopher Nolan

  "Animated Classics":
    smart_filter:
      any:
        genre: Animation
        studio: Pixar, Studio Ghibli
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/123923
    summary: Exceptional animated films from top studios

  "Harry Potter Collection":
    template: {name: Set, collection: 1241, poster: https://theposterdb.com/api/assets/21880, summary:}