templates:
  set:
    optional:
      - network
      - list
    tmdb_network: <<network>>
    tmdb_list: <<list>>
    sort_title: <<collection_name>>
    sync_mode: sync
    url_poster: <<poster>>
    url_background: <<background>>
  
  Genre:
    smart_filter:
      genre: <<genre>>
    sort_title: <<collection_name>>
    sync_mode: sync
    url_poster: <<poster>>
  
  TraktList:
    trakt_list: <<trakt_list>>
    sort_title: <<collection_name>>
    sync_mode: sync
    url_poster: <<poster>>

collections:
  # Existing Franchise Collections
  "DC Universe":
    template: { name: set, list: "8215646", poster: https://theposterdb.com/api/assets/239356, background: https://i.imgur.com/x9ijxTc.jpg }
    summary: Iconic DC Television Series

  "Marvel Television":
    template: { name: set, list: "8205726", poster: https://theposterdb.com/api/assets/239453, background: https://i.imgur.com/ckx6reE.jpg }
    summary: Marvel's Television Universe

  "Stargate":
    template: { name: set, list: "8205729", poster: https://theposterdb.com/api/assets/228932, background: https://i.imgur.com/VrJ3Um8.jpg }
    summary: All Stargate Series

  "Star Wars":
    template: { name: set, list: "8205730", poster: https://theposterdb.com/api/assets/164120, background: https://i.imgur.com/OvxROTE.jpg }
    summary: Star Wars Television Series

  "Star Trek":
    template: { name: set, list: "8215091", poster: https://theposterdb.com/api/assets/222279, background: https://i.imgur.com/Yp0NCZa.jpg }
    summary: Complete Star Trek Series

  # Genre Collections
  "Animated Series":
    template: { name: Genre, genre: Animation, poster: https://theposterdb.com/api/assets/239457 }
    summary: Best Animated Television Series

  "Sci-Fi Series":
    template: { name: Genre, genre: Sci-Fi, poster: https://theposterdb.com/api/assets/239458 }
    summary: Science Fiction Television Shows

  "Comedy Series":
    template: { name: Genre, genre: Comedy, poster: https://theposterdb.com/api/assets/239459 }
    summary: Hilarious Comedy Shows

  # Curated Collections
  "Critically Acclaimed Series":
    smart_filter:
      any:
        critic_rating.gt: 85
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239460
    summary: Television Series with Highest Critical Acclaim

  "Award-Winning Series":
    smart_filter:
      all:
        awards: emmy
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239461
    summary: Emmy Award-Winning Television Series

  # Specific Collections Based on Your Library
  "Animated Superhero Series":
    smart_filter:
      all:
        genre: Animation
        genre: Superhero
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239462
    summary: Animated Superhero Television Series

  "David Attenborough Nature Documentaries":
    smart_filter:
      any:
        title: 
          - "Planet Earth"
          - "Planet Earth III"
          - "Blue Planet"
          - "Blue Planet II"
          - "Frozen Planet"
          - "Frozen Planet II"
          - "Earthsounds"
          - "Seven Worlds, One Planet"
          - "Human Planet"
          - "The Green Planet"
          - "Earth at Night in Color"
          - "Cosmos"
          - "Tiny World"
          - "Secret World of Sound with David Attenborough"
          - "Secrets of the Octopus"
          - "Dynasties"
          - "Mammals"
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239463
    summary: Nature Documentary Series Featuring David Attenborough

  "Anime Collection":
    smart_filter:
      any:
        genre: Anime
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239464
    summary: Japanese Animated Television Series

  "Superhero Series":
    smart_filter:
      any:
        genre: Superhero
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239465
    summary: Television Series Featuring Superheroes

  # Director/Network Based Collections
  "Adult Swim Originals":
    smart_filter:
      any:
        network: Adult Swim
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239466
    summary: Unique Series from Adult Swim Network

  "HBO Prestige Series":
    smart_filter:
      any:
        network: HBO
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239467
    summary: High-Quality HBO Original Series

  # Custom Ordering Example
  "My Favorite Shows":
    smart_filter:
      any:
        title: "The Wire"
        title: "Breaking Bad"
        title: "The Sopranos"
    sync_mode: sync
    collection_order: custom
    sort_title:
      "The Wire": "01"
      "Breaking Bad": "02"
      "The Sopranos": "03"
    url_poster: https://theposterdb.com/api/assets/239468 # Example Poster
    summary: "My personal favorite TV shows."

  # Audience Rating Example
  "Highly Rated Shows":
    smart_filter:
      any:
        audience_rating.gt: 85
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239469 # Example Poster
    summary: "TV Shows with high audience ratings."

  # Trakt Example
  "Trakt Watchlist":
    template: {name: TraktList, trakt_list: "your_trakt_username/watchlist", poster: https://theposterdb.com/api/assets/239470 } #Replace "your_trakt_username"
    summary: Shows on my Trakt watchlist.