templates:
  set:
    optional:
      - network
      - list
    tmdb_network: <<network>>
    tmdb_list: <<list>>
    sort_title: <<collection_name>>
    sync_mode: sync
    url_poster: <<poster>>
    url_background: <<background>>
  Genre:
    smart_filter:
      genre: <<genre>>
    sort_title: <<collection_name>>
    sync_mode: sync
    url_poster: <<poster>>
  TraktList:
    trakt_list: <<trakt_list>>
    sort_title: <<collection_name>>
    sync_mode: sync
    url_poster: <<poster>>

collections:
  # Major Franchise & Universe Collections
  "DC Universe":
    template: { name: set, list: "8215646", poster: https://theposterdb.com/api/assets/239356, background: https://i.imgur.com/x9ijxTc.jpg }
    summary: Iconic DC Television Series
  "Marvel Television":
    template: { name: set, list: "8205726", poster: https://theposterdb.com/api/assets/239453, background: https://i.imgur.com/ckx6reE.jpg }
    summary: Marvel's Television Universe
  "Stargate":
    template: { name: set, list: "8205729", poster: https://theposterdb.com/api/assets/228932, background: https://i.imgur.com/VrJ3Um8.jpg }
    summary: All Stargate Series
  "Star Wars":
    template: { name: set, list: "8205730", poster: https://theposterdb.com/api/assets/164120, background: https://i.imgur.com/OvxROTE.jpg }
    summary: Star Wars Television Series
  "Star Trek":
    template: { name: set, list: "8215091", poster: https://theposterdb.com/api/assets/222279, background: https://i.imgur.com/Yp0NCZa.jpg }
    summary: Complete Star Trek Series
  "Doctor Who":
    template: { name: set, list: "8215100", poster: https://theposterdb.com/api/assets/239471, background: https://i.imgur.com/doctorwho.jpg }
    summary: All Doctor Who Series

  # Genre Collections (expand as needed)
  "Animated Series":
    template: { name: Genre, genre: Animation, poster: https://theposterdb.com/api/assets/239457 }
    summary: Best Animated Television Series
  "Anime Series":
    template: { name: Genre, genre: Anime, poster: https://theposterdb.com/api/assets/239464 }
    summary: Japanese Animated Television Series
  "Comedy Series":
    template: { name: Genre, genre: Comedy, poster: https://theposterdb.com/api/assets/239459 }
    summary: Hilarious Comedy Shows
  "Drama Series":
    template: { name: Genre, genre: Drama, poster: https://theposterdb.com/api/assets/239472 }
    summary: Gripping Drama Series
  "Crime Series":
    template: { name: Genre, genre: Crime, poster: https://theposterdb.com/api/assets/239473 }
    summary: Crime and Detective Shows
  "Documentary Series":
    template: { name: Genre, genre: Documentary, poster: https://theposterdb.com/api/assets/239474 }
    summary: Factual and Documentary Series
  "Family Series":
    template: { name: Genre, genre: Family, poster: https://theposterdb.com/api/assets/239475 }
    summary: Family-Friendly TV Shows
  "Fantasy Series":
    template: { name: Genre, genre: Fantasy, poster: https://theposterdb.com/api/assets/239476 }
    summary: Fantasy Television Series
  "Horror Series":
    template: { name: Genre, genre: Horror, poster: https://theposterdb.com/api/assets/239477 }
    summary: Horror and Supernatural TV
  "Mystery Series":
    template: { name: Genre, genre: Mystery, poster: https://theposterdb.com/api/assets/239478 }
    summary: Mystery and Suspense TV
  "Romance Series":
    template: { name: Genre, genre: Romance, poster: https://theposterdb.com/api/assets/239479 }
    summary: Romantic TV Shows
  "Sci-Fi Series":
    template: { name: Genre, genre: Sci-Fi, poster: https://theposterdb.com/api/assets/239458 }
    summary: Science Fiction Television Shows
  "Superhero Series":
    smart_filter:
      any:
        genre: Superhero
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239465
    summary: Television Series Featuring Superheroes
  "Animated Superhero Series":
    smart_filter:
      all:
        genre: Animation
        genre: Superhero
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239462
    summary: Animated Superhero Television Series

  # Curated & Critic Collections
  "Critically Acclaimed Series":
    smart_filter:
      any:
        critic_rating.gt: 85
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239460
    summary: Television Series with Highest Critical Acclaim
  "Award-Winning Series":
    smart_filter:
      all:
        awards: emmy
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239461
    summary: Emmy Award-Winning Television Series
  "Highly Rated Shows":
    smart_filter:
      any:
        audience_rating.gt: 85
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239469
    summary: TV Shows with high audience ratings.

  # Network & Studio Collections
  "Adult Swim Originals":
    smart_filter:
      any:
        network: Adult Swim
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239466
    summary: Unique Series from Adult Swim Network
  "HBO Prestige Series":
    smart_filter:
      any:
        network: HBO
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239467
    summary: High-Quality HBO Original Series
  "BBC Dramas":
    smart_filter:
      any:
        network: BBC One
        network: BBC Two
        network: BBC Three
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239480
    summary: Acclaimed Dramas from the BBC
  "Netflix Originals":
    smart_filter:
      any:
        network: Netflix
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239481
    summary: Original Series from Netflix
  "Apple TV+ Originals":
    smart_filter:
      any:
        network: Apple TV+
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239482
    summary: Original Series from Apple TV+
  "Amazon Prime Originals":
    smart_filter:
      any:
        network: Amazon
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239483
    summary: Original Series from Amazon Prime Video

  # Nature, Documentary & Special Interest
  "David Attenborough Nature Documentaries":
    smart_filter:
      any:
        title:
          - "Planet Earth"
          - "Planet Earth III"
          - "Blue Planet"
          - "Blue Planet II"
          - "Frozen Planet"
          - "Frozen Planet II"
          - "Earthsounds"
          - "Seven Worlds, One Planet"
          - "Human Planet"
          - "The Green Planet"
          - "Earth at Night in Color"
          - "Cosmos"
          - "Tiny World"
          - "Secret World of Sound with David Attenborough"
          - "Secrets of the Octopus"
          - "Dynasties"
          - "Mammals"
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239463
    summary: Nature Documentary Series Featuring David Attenborough

  # Anime & Japanese Collections
  "Anime Collection":
    smart_filter:
      any:
        genre: Anime
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239464
    summary: Japanese Animated Television Series
  "Japanese Drama":
    smart_filter:
      any:
        country: Japan
        language: Japanese
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239484
    summary: Japanese Live-Action TV Dramas

  # Kids & Family
  "Kids Shows":
    smart_filter:
      any:
        genre: Kids
        genre: Children
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/239485
    summary: TV Shows for Kids and Families

  # Personal & Custom
  "My Favorite Shows":
    smart_filter:
      any:
        title: "The Wire"
        title: "Breaking Bad"
        title: "The Sopranos"
    sync_mode: sync
    collection_order: custom
    sort_title:
      "The Wire": "01"
      "Breaking Bad": "02"
      "The Sopranos": "03"
    url_poster: https://theposterdb.com/api/assets/239468
    summary: "My personal favorite TV shows."

  # Trakt Integration Example
  "Trakt Watchlist":
    template: {name: TraktList, trakt_list: "your_trakt_username/watchlist", poster: https://theposterdb.com/api/assets/239470 }
    summary: Shows on my Trakt watchlist.

  # Add further custom, director, or curated collections below as needed.
