services:
#External Hompage Dashboard
  homer:
    image: b4bz/homer:latest
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - ${CONFIG}/homer-ext/assets:/www/assets
    ports:
      - 9090:8080
    environment:
      PUID: ${PUID} # optional, your user id
      PGID: ${PGID} # optional, your group id
      TZ: ${TZ}
    restart: unless-stopped

#Watchtower - update Docker Containers automatically
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 86400
    environment:
      - WATCHTOWER_CLEANUP=true
      - TZ=${TZ}
    restart: unless-stopped