services:
  postgresus:
    container_name: postgresdb_backups-postgresus
    image: rostislavdugin/postgresus:latest
    ports:
      - "4005:4005"
    volumes:
      - ./postgresus-data:/postgresus-data
    restart: unless-stopped
    networks:
      - backend
      - frontend
networks:
  frontend:
    external: true
  backend:
    external: true