services:
    plextraktsync:
        image: ghcr.io/taxel/plextraktsync:latest
        command: sync
        container_name: plextraktsync
        restart: on-failure:2
        volumes:
            - ${CONFIG}/plextraktsync:/app/config
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        #PlexTraktSync Watch
        labels:
            # Watchtower
            - "com.centurylinklabs.watchtower.enable=true"
    plextraktsyncwatch:
        image: ghcr.io/taxel/plextraktsync:latest
        container_name: plextraktsyncwatch
        volumes:
            - ${CONFIG}/plextraktsync:/app/config
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        command: watch
        restart: always
        labels:
            # Watchtower
            - "com.centurylinklabs.watchtower.enable=true"
#Schedule PlexTraktSync to run daily
    scheduler:
        image: mcuadros/ofelia:latest
        container_name: scheduler
        depends_on:
            - plextraktsync
        command: daemon --docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: always
        labels:
            ofelia.job-run.plextraktsync.schedule: "0 2 * * *"
            ofelia.job-run.plextraktsync.container: "plextraktsync"
            com.centurylinklabs.watchtower.enable: "true"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}