services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-ovh001
    restart: unless-stopped
    volumes:
      - ./config:/root/.cloudflared
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - TZ=Europe/London
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true