services:
  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    restart: always
    ports:
      - "9705:9705"
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/London
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.60
networks:
  servarrnetwork:
    external: true