services:
  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    restart: always
    ports:
      - "9705:9705"
    volumes:
      - ${CONFIG}/huntarr:/config
    environment:
      - TZ=Europe/London
    labels:
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  servarrnetwork:
    external: true