services:
  cloudflared:
    container_name: app-cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - frontend
      - backend
networks:
  frontend:
    external: true
  backend:
    external: true