networks:
  keydb:
  mongo:

services:
  heyform:
    image: heyform/community-edition:latest
    container_name: heyform
    restart: always
    volumes:
      - ./assets:/app/static/upload
    depends_on:
      - mongo
      - redis
    ports:
      - '9513:8000'
    environment:
      APP_HOMEPAGE_URL: ${APP_HOMEPAGE}
      SESSION_KEY: ${SESSION_KEY}
      FORM_ENCRYPTION_KEY: ${FORM_ENCRYPTION_KEY}
      #MongoDB
      # MONGO_USER: ${MONGO_USER}
      # MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_URI: 'mongodb://mongo:27017/heyform'
      #Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # REDIS_PASSWORD: ${REDIS_PASSWORD}
      #Unsplash
      UNSPLASH_CLIENT_ID: ${UNSPLASH_CLIENT_ID}
      #Mail
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      #SMTP_SECURE: ${SMTP_SECURE}
      #SMTP_IGNORE_CERT: ${SMTP_IGNORE_CERT}
    networks:
      - mongo
      - keydb

  mongo:
    image: mongo:4.4.18
    container_name: heform-mongo
    restart: always
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - mongo
    command: --wiredTigerCacheSizeGB 0.25
    # environment:
    #   MONGO_USER: ${MONGO_USER}
    #   MONGO_PASSWORD: ${MONGO_PASSWORD}

  redis:
    image: redis:alpine
    container_name: heyform-redis
    restart: always
    command: redis-server --appendonly yes --protected-mode no
    volumes:
      - ./redis_data:/data
    networks:
      - keydb
    # environment:
    #   REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  mongodb_data:
  redis_data: