networks:
  heyform-main:
    name: heyform-main
  frontend:
    external: true
  backend:
    external: true

services:
  heyform:
    image: heyform/community-edition:latest
    container_name: heyform
    restart: always
    volumes:
      - ./assets:/app/static/upload
    env_file: .env
    environment:
      # Use HTTPS to match cookie expectations
      APP_HOMEPAGE_URL: https://forms.${DOMAIN}
      TRUST_PROXY: 1
      SESSION_KEY: ${SESSION_KEY}
      FORM_ENCRYPTION_KEY: ${FORM_ENCRYPTION_KEY}
      APP_LISTEN_PORT: 8000

      # MongoDB
      MONGO_URI: mongodb://mongo:27017/heyform

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # Unsplash
      UNSPLASH_CLIENT_ID: ${UNSPLASH_CLIENT_ID}

      # Mail
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}

    depends_on:
      - mongo
      - redis

    networks:
      - frontend
      - backend
      - heyform-main

    labels:
      - "traefik.enable=true"

      # Insecure HTTP router (for redirect)
      - "traefik.http.routers.heyform.rule=Host(`forms.${DOMAIN}`)||Host(`forms.apps.${DOMAIN}`)"
      - "traefik.http.routers.heyform.entrypoints=http"
      - "traefik.http.middlewares.heyform-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.heyform.middlewares=heyform-https-redirect"

      # Secure HTTPS router
      - "traefik.http.routers.heyform-secure.rule=Host(`forms.${DOMAIN}`)||Host(`forms.apps.${DOMAIN}`)"
      - "traefik.http.routers.heyform-secure.entrypoints=https"
      - "traefik.http.routers.heyform-secure.tls=true"
      - "traefik.http.routers.heyform-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.heyform-secure.service=heyform-service"

      # Expose internal app port 8000 to Traefik
      - "traefik.http.services.heyform-service.loadbalancer.server.port=8000"

  mongo:
    image: mongo:4.4.18
    container_name: mongo
    restart: always
    volumes:
      - ./config/mongodb_data:/data/db
    networks:
      - heyform-main
    command: --wiredTigerCacheSizeGB 0.25

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server --appendonly yes --protected-mode no
    volumes:
      - ./config/redis_data:/data
    networks:
      - heyform-main

volumes:
  mongodb_data:
  redis_data: