services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer

    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/data