services:
#Bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config #Bazarr Config
      - ${MOVIES}:/movies #Movies Folder
      - ${TVSHOWS}:/tv #TV Shows Folder
    ports:
      - 6767:6767
    networks:
      servarrnetwork: 
        ipv4_address: 172.69.0.50
# labels:
    restart: unless-stopped
networks:
  servarrnetwork:
    external: true