services:
  nginx:
    image: nginx:latest
    container_name: mickey7-nginx
    restart: unless-stopped
    volumes:
      - ./config/templates:/etc/nginx/templates
      - ./config/html:/usr/share/nginx/html
    environment:
      - NGINX_HOST=mickey21.${DOMAIN}
      - NGINX_PORT=80
      - TZ=Europe/London
      - PGID=1000
      - PUID=1000
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      # HTTP Router (for redirect)
      - traefik.http.routers.mickey21-http.rule=Host(`mickey21.${DOMAIN}`)
      - traefik.http.routers.mickey21-http.entrypoints=web
      # HTTPS Router
      - traefik.http.routers.mickey21-https.tls=true
      - traefik.http.routers.mickey21-https.tls.certresolver=cloudflare
      - traefik.http.routers.mickey21-https.entrypoints=websecure
      - traefik.http.routers.mickey21-https.rule=Host(`mickey21.${DOMAIN}`)

      - "com.centurylinklabs.watchtower.enable=true"

networks:
  frontend:
    external: true