services:
  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /srv/dev-disk-by-uuid-e902b840-5280-4b1d-a0be-27da08be904a/gigaplex/gigaplex-data/next-cloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=9RHM#VwAHgBstl       # Replace with a strong password
      - MYSQL_PASSWORD=@4Mp!nFFMLVJyF            # Replace with a strong password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud_net

  app:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8085:80
    volumes:
      - /srv/dev-disk-by-uuid-e902b840-5280-4b1d-a0be-27da08be904a/gigaplex/gigaplex-data/next-cloud/html:/var/www/html
    environment:
      - MYSQL_PASSWORD=@4Mp!nFFMLVJyF            # Same as in db service
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=office.gigaplex.site 192.168.1.200:8085
    networks:
      - nextcloud_net

networks:
  nextcloud_net:
    driver: bridge
