services:
#Gluetun - VPN Container
  gluetun:
      image: qmcgaw/gluetun:latest
      container_name: gluetun
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun:/dev/net/tun
      restart: unless-stopped
      ports:
        - 6881:6881
        - 6881:6881/udp # Transmission

        - 8081:8081 # QBittorrent

        - 8989:8989 # Sonarr
        - 7878:7878 # Radarr
        - 9696:9696 # Prowlarr

      volumes:
        - ./config:/gluetun
      environment:
        - TZ=${TZ}
        - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
        - VPN_TYPE=${VPN_TYPE}
        - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
        - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
        - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
        - SERVER_COUNTRIES=${SERVER_COUNTRIES}
