services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    container_name: karakeep
    restart: always
    env_file: .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      TZ: Europe/London
    volumes:
      - ./config/karakeep/data:/data
    depends_on:
      - meilisearch
      - chrome
    networks:
      - karakeep
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      # HTTP Router (for redirect)
      - "traefik.http.routers.karakeep.entrypoints=http"
      - "traefik.http.routers.karakeep.rule=Host(`read.${DOMAIN}`)||Host(`read.apps.${DOMAIN}`)" # Expose both outside and the internal domains for Traefik
      - "traefik.http.middlewares.karakeep-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.routers.karakeep.middlewares=karakeep-https-redirect"
      # HTTPS Router
      - "traefik.http.routers.karakeep-secure.entrypoints=https"
      - "traefik.http.routers.karakeep-secure.rule=Host(`read.${DOMAIN}`)||Host(`read.apps.${DOMAIN}`)" # Expose both outside and the internal domains for Traefik
      - "traefik.http.routers.karakeep-secure.tls=true"
      - "traefik.http.routers.karakeep-secure.tls.certresolver=cloudflare"
      # Service configuration
      - "traefik.http.routers.karakeep.middlewares=authentik-auth@file"
      - "traefik.http.routers.karakeep-secure.service=karakeep-service"
      - "traefik.http.services.karakeep-service.loadbalancer.server.port=3000"

  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: karakeep-meilisearch
    restart: always
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./config/meilisearch/meili_data:/meili_data
    networks:
      - karakeep
      - backend

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep-chrome
    restart: always
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - karakeep
      - backend

networks:
  karakeep:
    external: true
  frontend:
    external: true
  backend:
    external: true
