services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped

#Node RED
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - /srv/dev-disk-by-uuid-e902b840-5280-4b1d-a0be-27da08be904a/gigaplex/gigaplex-data/nodered:/data
    environment:
      - TZ=Europe/London
    restart: unless-stopped

volumes:
  grafana-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/dev-disk-by-uuid-e902b840-5280-4b1d-a0be-27da08be904a/gigaplex/gigaplex-data/grafana
  influxdb-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/dev-disk-by-uuid-e902b840-5280-4b1d-a0be-27da08be904a/gigaplex/gigaplex-data/influxdb/
