services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - ./backrest/tmp:/tmp
      - ./backrest/rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      # Mount local paths to backup
      - ${GIGAPLEX_CONFIGS}:/gigaplex-configs:ro
      - ${GIGAPLEX_DATA}:/gigaplex-data:ro
      - ${PORTFOLIO_IMAGES}:/portfolio-images:ro
      
      - ${APPS_PI}:/gigaplex-apps:ro
      #- /path/to/local/repos:/repos     # Mount local repos (optional for remote storage)
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    ports:
      - "9898:9898"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    external: true